name: Development Branch CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  PYTHON_VERSION: '3.9'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run Tests
        run: |
          pytest || if [ $? -eq 5 ]; then
            echo "No tests found - treating as success"
            exit 0
          else
            exit $?
          fi

  merge-to-main:
    name: Merge to Main
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Fetch all branches
        run: |
          git fetch origin
          
      - name: Create main branch if it doesn't exist
        run: |
          if ! git show-ref --verify refs/remotes/origin/main; then
            echo "Creating main branch..."
            git checkout -b main
            git push -u origin main
          else
            git checkout main || git checkout -b main origin/main
          fi
          
      - name: Merge to Main
        run: |
          git merge --no-ff dev -m "Merge dev into main"
          git push origin main